../../scarlet/scarlet -n main -s \
test.scar \
src/helpers/custom.scar \
src/helpers/float.scar \
src/helpers/heap_data.scar \
src/helpers/other.scar \
src/helpers/rnd_data.scar \
src/__add__.scar \
src/__and__.scar \
src/__ashr__.scar \
src/__concat__.scar \
src/__div__.scar \
src/__equal__.scar \
src/__get_item__.scar \
src/__get_field__.scar \
src/__great__.scar \
src/__great_or_eq__.scar \
src/__less__.scar \
src/__less_or_eq__.scar \
src/__lshr__.scar \
src/__mod__.scar \
src/__mul__.scar \
src/__not_equal__.scar \
src/__or__.scar \
src/__shl__.scar \
src/__slice__.scar \
src/__strong_equal__.scar \
src/__strong_not_equal__.scar \
src/__sub__.scar \
src/__xor__.scar \
src/abs.scar \
src/acos.scar \
src/all_kv.scar \
src/all.scar \
src/any_kv.scar \
src/any.scar \
src/append_new.scar \
src/append.scar \
src/ascii_to_lower.scar \
src/ascii_to_upper.scar \
src/asin.scar \
src/assemble_time.scar \
src/atan.scar \
src/box_len.scar \
src/break.scar \
src/call_stack.scar \
src/cap.scar \
src/ceil.scar \
src/char_lang.scar \
src/char_to_uchar.scar \
src/clear.scar \
src/cmp.scar \
src/common.scar \
src/copy.scar \
src/cos.scar \
src/day.scar \
src/delete.scar \
src/disassemble_time.scar \
src/drop_while.scar \
src/drop.scar \
src/dump.scar \
src/duration.scar \
src/each_to_each.scar \
src/each_to_each_kv.scar \
src/empty_val.scar \
src/exp.scar \
src/exp2.scar \
src/filter_kv.scar \
src/filter.scar \
src/first.scar \
src/floor.scar \
src/foldl_kv.scar \
src/foldl.scar \
src/foldl1.scar \
src/foldr_kv.scar \
src/foldr.scar \
src/foldr1.scar \
src/format_int.scar \
src/gconsts.scar \
src/get_error_id_msg_data.scar \
src/hash.scar \
src/hour.scar \
src/implement.scar \
src/in.scar \
src/inherits_from.scar \
src/init.scar \
src/insert_part_to.scar \
src/insert_to.scar \
src/int_to_time.scar \
src/is_ascii_ctrl.scar \
src/is_ascii_digit.scar \
src/is_ascii_graphic.scar \
src/is_ascii_letter.scar \
src/is_ascii_lower.scar \
src/is_ascii_space.scar \
src/is_ascii_symbol.scar \
src/is_ascii_upper.scar \
src/is_ascii.scar \
src/is_ctrl.scar \
src/is_digit.scar \
src/is_empty.scar \
src/is_error.scar \
src/is_even.scar \
src/is_graphic.scar \
src/is_in_range.scar \
src/is_inf.scar \
src/is_letter.scar \
src/is_lower.scar \
src/is_nan.scar \
src/is_neg_inf.scar \
src/is_null.scar \
src/is_odd.scar \
src/is_short_type.scar \
src/is_space.scar \
src/is_symbol.scar \
src/is_uncopyable_error.scar \
src/is_upper.scar \
src/join.scar \
src/key_of.scar \
src/last.scar \
src/len.scar \
src/log__debug_msg.scar \
src/log__msg.scar \
src/log.scar \
src/log2.scar \
src/log10.scar \
src/look_from_end_in.scar \
src/look_in.scar \
src/look_other_from_end_in.scar \
src/look_other_in.scar \
src/look_part_from_end_in.scar \
src/look_part_in.scar \
src/loop.scar \
src/make_channel.scar \
src/map_kv.scar \
src/map_with_state.scar \
src/map_kv_with_state.scar \
src/map.scar \
src/max_val.scar \
src/max.scar \
src/min_val.scar \
src/min.scar \
src/minute.scar \
src/month.scar \
src/move.scar \
src/multithread__share.scar \
src/neg_bits.scar \
src/neg.scar \
src/not.scar \
src/obj_to_table.scar \
src/ok_check.scar \
src/operator__new.scar \
src/parse_int.scar \
src/part_of.scar \
src/pop__push.scar \
src/power.scar \
src/prefix_of.scar \
src/print.scar \
src/println.scar \
src/qty_0_bits.scar \
src/qty_1_bits.scar \
src/qty_leading_0_bits.scar \
src/qty_leading_1_bits.scar \
src/qty_trailing_0_bits.scar \
src/qty_trailing_1_bits.scar \
src/qty.scar \
src/read_from_mem.scar \
src/remove.scar \
src/repeat.scar \
src/replace_part.scar \
src/replace.scar \
src/reserve.scar \
src/reverse_bits.scar \
src/reverse_bytes.scar \
src/reverse.scar \
src/rnd.scar \
src/rotate_left.scar \
src/rotate_right.scar \
src/round.scar \
src/scarlet__erase_info.scar \
src/scarlet__erase_value.scar \
src/scarlet__join_unsafe.scar \
src/scarlet__rnd.scar \
src/scarlet__split_unsafe.scar \
src/second.scar \
src/self_copy.scar \
src/serialize__deserialize.scar \
src/set_log_level.scar \
src/shuffle_box.scar \
src/sin.scar \
src/sleep.scar \
src/sort_fn.scar \
src/sort.scar \
src/split_by_part.scar \
src/split.scar \
src/sqr.scar \
src/sqrt.scar \
src/stable_sort_fn.scar \
src/stable_sort.scar \
src/str_to_tkn.scar \
src/str_to_ustr.scar \
src/suffix_of.scar \
src/table_to_obj.scar \
src/take_one_kv.scar \
src/take_one.scar \
src/take_while.scar \
src/take.scar \
src/tan.scar \
src/thread.scar \
src/time_limit_pop.scar \
src/time_limit_wait.scar \
src/time.scar \
src/timezone.scar \
src/to_array.scar \
src/to_bool.scar \
src/to_box.scar \
src/to_byte.scar \
src/to_char.scar \
src/to_float.scar \
src/to_int.scar \
src/to_lower.scar \
src/to_string.scar \
src/to_upper.scar \
src/trim.scar \
src/trunc.scar \
src/type.scar \
src/uchar_to_ustr.scar \
src/unslice.scar \
src/uprint.scar \
src/uprintln.scar \
src/ustr_to_str.scar \
src/wait.scar \
src/write_to_mem.scar \
src/year.scar \
src/yield.scar \
src/zip_n.scar \
src/zip.scar \
-o test.c &&
clang -march=native -pthread -std=c23 -DFULL_DEBUG -fsanitize=address -fsanitize=undefined -g -O0 -c src/helpers/custom.c -o custom.o &&
clang -march=native -pthread -lm -std=c23 -DEXPORT_CORE -DFULL_DEBUG -fsanitize=address -fsanitize=undefined -g -O0 custom.o test.c -o test &&
./test
